### PR TITLE
Sync new features and bugfixs from f0b1c219

### PR DESCRIPTION
**Pull request by embbnux**
style(meetingPanel): fix meeting enabled join before host  text overflow
refactor: use events to replace event-emitter
feat(Meeting Component): Enhancement of Meeting Panel component
feat(commons/userGuide): change take a quick tour to common scence
style(canvas/meetingListPage): rewrite the meeting list page UI
fix(AdapterCore): fix presence dropdown
fix(commons/CircleButton): fix the issue of hang up or make a call when clicking blank place
fix(MeetingItem): fix horizontal alignment
feat(userGuide): enhancement of user guide
fix(contact match): add contact match for Softphone and RingOut modules

### CODE REVIEW

**Comment by embbnux** [comment]
rerun

**Comment by sylviawangfr** [comment]
rerun

**Comment by sylviawangfr** [comment]
rerun

**Comment by sylviawangfr** [comment]
rerun

**Comment by sylviawangfr** [comment]
rerun

**Comment by sylviawangfr** [comment]
rerun

**Pull request merged**
